# Generated by Django 2.1.7 on 2019-03-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190324_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '선택하기'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '질문하기'},
        ),
    ]
